# fly.toml app configuration file generated for fake-email-diego on 2024-03-27T09:24:31-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fake-email-diego'
primary_region = 'ord'

[experimental]
  auto_rollback = true

[build]

[env]
  PORT = '8080'

[[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

[http_service]
  internal_port = 8080
  internal_address = "0.0.0.0"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
